POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Ankara myrsky",
    "author": "Pekka Poutaniemi",
    "url": "yle.fi",
    "likes": 36,
    "userId": "697f49c50d595199d86f2ecf"
}